name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  python:
    uses: matheussiqueirahub/banco_aurora/.github/workflows/python-ci.yml@main
    with:
      matrix-os: '["ubuntu-latest"]'
      python-versions: '["3.11"]'
      run-lint: true
      run-tests: false
      post-run: |
        python - <<'PY'
        from infra.forja_persistencia import ForjaDePersistencia
        from services.servicos import OrquestradorDeFluxoComercial
        from services import relatorios as rel
        from api.main import app
        # Banco local (cria data/)
        f = ForjaDePersistencia()
        f.criar_esquema()
        conn = f.conectar()
        try:
            svc = OrquestradorDeFluxoComercial(conn)
            prods = svc.listar_produtos()
            if not prods:
                p = svc.cadastrar_produto('CI Produto', 'Smoke', 3, 10.0)
                svc.registrar_venda(p.id, 1)
            receita = rel.receita_total(conn)
            assert receita >= 10.0, receita
        finally:
            conn.close()
        from fastapi.testclient import TestClient
        c = TestClient(app)
        r = c.get('/produtos')
        assert r.status_code == 200, r.text
        print('smoke ok')
        PY
